// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnhchqoaibdmcwtcxtal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuaGNocW9haWJkbWN3dGN4dGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzcyOTIsImV4cCI6MjA3MzUxMzI5Mn0.0X1ssN_pj-Nz4a-24Xm99O4tg6zLcUyYRKlQkeAb04Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});